### ISSUE TITLE
A few ppc64le packages are missing

### ISSUE THREAD

**Issue by ericpre** [conda-forge/traits-feedstock#28]
The merge build on travis didn't complete successfully and some ppc64le packages are missing:
https://github.com/conda-forge/traits-feedstock/runs/1742537289
https://travis-ci.com/github/conda-forge/traits-feedstock/builds/213947522

**Comment by grlee77** [comment]
I think this was resolved when #29 was merged. Please reopen if there is still a problem

**Comment by ericpre** [comment]
Yes, this is correct, thanks for following up! I could have close it earlier myself!
It seems that the ppc64le build situation on travis have improved, but there are still some random failure.
